{
    imports = [
        ./git.nix
        ./fzf.nix
        ./starship/starship.nix
        ./starship/toggle/starship-toggle.nix
        ./kitty.nix
        ./lsd/lsd.nix
        #./swww.nix
        ./tmux.nix
        ./hypr/hyprland.nix
        ./hypr/hypridle/hypridle.nix
        ./spicetify.nix
        #./vscode.nix
        ./waybar/waybar.nix
        ./waybar/scripts/waybar-toggle.nix
        ./waybar/scripts/waybar-restart.nix
        ./librewolf/librewolf.nix
	  ]; 
}
